# Generated by Django 4.1.3 on 2023-01-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribedmails',
            options={'verbose_name_plural': 'Subscribed Emails'},
        ),
        migrations.AlterField(
            model_name='subscribedmails',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
