# Generated by Django 4.1.3 on 2023-01-03 16:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='long_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
