# Generated by Django 4.1.3 on 2022-12-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_tax_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_data',
            field=models.JSONField(blank=True, help_text="Data format:{vendor1: {'tax_type':{'tax_percentage':'tax_amount'}}}", null=True),
        ),
    ]
